//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stundenplan.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Stundenplan.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string ApplicationBarAdd {
            get {
                return ResourceManager.GetString("ApplicationBarAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clear.
        /// </summary>
        public static string ApplicationBarCleanUp {
            get {
                return ResourceManager.GetString("ApplicationBarCleanUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string ApplicationBarDelete {
            get {
                return ResourceManager.GetString("ApplicationBarDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string ApplicationBarDone {
            get {
                return ResourceManager.GetString("ApplicationBarDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to homework.
        /// </summary>
        public static string ApplicationBarHomework {
            get {
                return ResourceManager.GetString("ApplicationBarHomework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import.
        /// </summary>
        public static string ApplicationBarImport {
            get {
                return ResourceManager.GetString("ApplicationBarImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to live tile.
        /// </summary>
        public static string ApplicationBarLiveTile {
            get {
                return ResourceManager.GetString("ApplicationBarLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test dates.
        /// </summary>
        public static string ApplicationBarNotes {
            get {
                return ResourceManager.GetString("ApplicationBarNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report.
        /// </summary>
        public static string ApplicationBarReport {
            get {
                return ResourceManager.GetString("ApplicationBarReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save.
        /// </summary>
        public static string ApplicationBarSave {
            get {
                return ResourceManager.GetString("ApplicationBarSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sort.
        /// </summary>
        public static string ApplicationBarSort {
            get {
                return ResourceManager.GetString("ApplicationBarSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern Timetable.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MODERN TIMETABLE.
        /// </summary>
        public static string AppNameUpperCase {
            get {
                return ResourceManager.GetString("AppNameUpperCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After this error, the app needs to be rebooted. We apologize for the inconvenience..
        /// </summary>
        public static string AppNavigationFailedWarning {
            get {
                return ResourceManager.GetString("AppNavigationFailedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial.
        /// </summary>
        public static string AppTrial {
            get {
                return ResourceManager.GetString("AppTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to done.
        /// </summary>
        public static string BooleanDone {
            get {
                return ResourceManager.GetString("BooleanDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not done.
        /// </summary>
        public static string BooleanNotDone {
            get {
                return ResourceManager.GetString("BooleanNotDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove.
        /// </summary>
        public static string ContextMenuDelete {
            get {
                return ResourceManager.GetString("ContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download to device.
        /// </summary>
        public static string ContextMenuDownload {
            get {
                return ResourceManager.GetString("ContextMenuDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to duplicate.
        /// </summary>
        public static string ContextMenuDublicate {
            get {
                return ResourceManager.GetString("ContextMenuDublicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string ContextMenuEdit {
            get {
                return ResourceManager.GetString("ContextMenuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export.
        /// </summary>
        public static string ContextMenuExport {
            get {
                return ResourceManager.GetString("ContextMenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to view homework.
        /// </summary>
        public static string ContextMenuHomework {
            get {
                return ResourceManager.GetString("ContextMenuHomework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open.
        /// </summary>
        public static string ContextMenuOpen {
            get {
                return ResourceManager.GetString("ContextMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to rename.
        /// </summary>
        public static string ContextMenuRename {
            get {
                return ResourceManager.GetString("ContextMenuRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This day doesn&apos;t exist:.
        /// </summary>
        public static string ConvertHelpersDayOfWeekToStringException {
            get {
                return ResourceManager.GetString("ConvertHelpersDayOfWeekToStringException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Note.
        /// </summary>
        public static string DateNew {
            get {
                return ResourceManager.GetString("DateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Future.
        /// </summary>
        public static string DateTimeFuture {
            get {
                return ResourceManager.GetString("DateTimeFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past.
        /// </summary>
        public static string DateTimePast {
            get {
                return ResourceManager.GetString("DateTimePast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Month.
        /// </summary>
        public static string DateTimeThisMonth {
            get {
                return ResourceManager.GetString("DateTimeThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Week.
        /// </summary>
        public static string DateTimeThisWeek {
            get {
                return ResourceManager.GetString("DateTimeThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string DateTimeToday {
            get {
                return ResourceManager.GetString("DateTimeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tomorrow.
        /// </summary>
        public static string DateTimeTomorrow {
            get {
                return ResourceManager.GetString("DateTimeTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:t}
        ///{1:t}.
        /// </summary>
        public static string LessonTimeMultiLineFormat {
            get {
                return ResourceManager.GetString("LessonTimeMultiLineFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. Lesson.
        /// </summary>
        public static string LessonTimeNumberTextFormat {
            get {
                return ResourceManager.GetString("LessonTimeNumberTextFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:t}.
        /// </summary>
        public static string LessonTimeSingleLineEnd {
            get {
                return ResourceManager.GetString("LessonTimeSingleLineEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:t} -.
        /// </summary>
        public static string LessonTimeSingleLineStart {
            get {
                return ResourceManager.GetString("LessonTimeSingleLineStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This list is empty..
        /// </summary>
        public static string ListBoxEmptyStringDefault {
            get {
                return ResourceManager.GetString("ListBoxEmptyStringDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timetable could not be opened, reading an older backup also failed..
        /// </summary>
        public static string LoadSaveBackupFailed {
            get {
                return ResourceManager.GetString("LoadSaveBackupFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The timetable could not be opened, but an older backup could be restored..
        /// </summary>
        public static string LoadSaveBackupLoaded {
            get {
                return ResourceManager.GetString("LoadSaveBackupLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Backup-XML-File couldn&apos;t be found..
        /// </summary>
        public static string LoadSaveBackupNotFound {
            get {
                return ResourceManager.GetString("LoadSaveBackupNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup failed to load..
        /// </summary>
        public static string LoadSaveOnlyBackupFailure {
            get {
                return ResourceManager.GetString("LoadSaveOnlyBackupFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No up-to-date timetable data was found, but an older backup is available. Do you want to load it?.
        /// </summary>
        public static string LoadSaveOnlyBackupWarning {
            get {
                return ResourceManager.GetString("LoadSaveOnlyBackupWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current timetable could not be found. To prevent further data loss no other timetable was loaded..
        /// </summary>
        public static string LoadSaveOtherFailure {
            get {
                return ResourceManager.GetString("LoadSaveOtherFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///I am using {0} version {1} and the following error occurred:
        ///
        ///{2}
        ///
        ///Kind Regards..
        /// </summary>
        public static string LoadSaveReport {
            get {
                return ResourceManager.GetString("LoadSaveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First error: {0}
        ///Error message: {1}
        ///Error information: {2}
        ///.
        /// </summary>
        public static string LoadSaveReportPrimaryErrorFormat {
            get {
                return ResourceManager.GetString("LoadSaveReportPrimaryErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second error: {0}
        ///Error message: {1}
        ///Error information: {2}
        ///.
        /// </summary>
        public static string LoadSaveReportSecondaryErrorFormat {
            get {
                return ResourceManager.GetString("LoadSaveReportSecondaryErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable: I/O Error Report.
        /// </summary>
        public static string LoadSaveReportSubject {
            get {
                return ResourceManager.GetString("LoadSaveReportSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while saving: {0}.
        /// </summary>
        public static string LoadSaveSaveErrorFormat {
            get {
                return ResourceManager.GetString("LoadSaveSaveErrorFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///We would appreciate your error report to help us to resolve the issue in an upcoming patch..
        /// </summary>
        public static string LoadSaveWarningFormat {
            get {
                return ResourceManager.GetString("LoadSaveWarningFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string MessageBoxCriticalError {
            get {
                return ResourceManager.GetString("MessageBoxCriticalError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove this?.
        /// </summary>
        public static string MessageBoxRemoveCaption {
            get {
                return ResourceManager.GetString("MessageBoxRemoveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string MessageBoxWarningCaption {
            get {
                return ResourceManager.GetString("MessageBoxWarningCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string MessageDialogCancel {
            get {
                return ResourceManager.GetString("MessageDialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string MessageDialogOK {
            get {
                return ResourceManager.GetString("MessageDialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to open link.
        /// </summary>
        public static string OpenSourceLookAt {
            get {
                return ResourceManager.GetString("OpenSourceLookAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now an open source project and free in the store. I am afraid I do not have enough time myself to keep making updates for this app. So if you want to have a look at the code or maybe even write new features, here is the link to the project {1}..
        /// </summary>
        public static string OpenSourceMessage {
            get {
                return ResourceManager.GetString("OpenSourceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translation.
        /// </summary>
        public static string PageAboutPageTranslation {
            get {
                return ResourceManager.GetString("PageAboutPageTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test dates.
        /// </summary>
        public static string PageDateOverviewCaption {
            get {
                return ResourceManager.GetString("PageDateOverviewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No test dates.
        ///Tap + to add a test date!.
        /// </summary>
        public static string PageDateOverviewEmptyString {
            get {
                return ResourceManager.GetString("PageDateOverviewEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove this date?.
        /// </summary>
        public static string PageDateOverviewRemoveWarning {
            get {
                return ResourceManager.GetString("PageDateOverviewRemoveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test dates.
        /// </summary>
        public static string PageEditDateCaption {
            get {
                return ResourceManager.GetString("PageEditDateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test dates.
        /// </summary>
        public static string PageEditDateDate {
            get {
                return ResourceManager.GetString("PageEditDateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string PageEditDateName {
            get {
                return ResourceManager.GetString("PageEditDateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find test date..
        /// </summary>
        public static string PageEditDateNotFound {
            get {
                return ResourceManager.GetString("PageEditDateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        public static string PageEditDateRepetition {
            get {
                return ResourceManager.GetString("PageEditDateRepetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homework.
        /// </summary>
        public static string PageEditHomeworkCaption {
            get {
                return ResourceManager.GetString("PageEditHomeworkCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string PageEditHomeworkDescription {
            get {
                return ResourceManager.GetString("PageEditHomeworkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string PageEditHomeworkFromDate {
            get {
                return ResourceManager.GetString("PageEditHomeworkFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find homework..
        /// </summary>
        public static string PageEditHomeworkNotFoundWarning {
            get {
                return ResourceManager.GetString("PageEditHomeworkNotFoundWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove this homework?.
        /// </summary>
        public static string PageEditHomeworkRemoveWarning {
            get {
                return ResourceManager.GetString("PageEditHomeworkRemoveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose subject.
        /// </summary>
        public static string PageEditHomeworkSubject {
            get {
                return ResourceManager.GetString("PageEditHomeworkSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose due date.
        /// </summary>
        public static string PageEditHomeworkToDate {
            get {
                return ResourceManager.GetString("PageEditHomeworkToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        public static string PageEditLessonCaption {
            get {
                return ResourceManager.GetString("PageEditLessonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different times.
        /// </summary>
        public static string PageEditLessonCustomTimes {
            get {
                return ResourceManager.GetString("PageEditLessonCustomTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit subject.
        /// </summary>
        public static string PageEditLessonEditSubject {
            get {
                return ResourceManager.GetString("PageEditLessonEditSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        public static string PageEditLessonHeader {
            get {
                return ResourceManager.GetString("PageEditLessonHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add times for an additional lesson to proceed..
        /// </summary>
        public static string PageEditLessonNewLessonTimeWarning {
            get {
                return ResourceManager.GetString("PageEditLessonNewLessonTimeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new subject....
        /// </summary>
        public static string PageEditLessonNewSubject {
            get {
                return ResourceManager.GetString("PageEditLessonNewSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find lesson!.
        /// </summary>
        public static string PageEditLessonNotFoundWarning {
            get {
                return ResourceManager.GetString("PageEditLessonNotFoundWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odd weeks different.
        /// </summary>
        public static string PageEditLessonOddWeeks {
            get {
                return ResourceManager.GetString("PageEditLessonOddWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change default times.
        /// </summary>
        public static string PageEditLessonPageChangeDefaultTimes {
            get {
                return ResourceManager.GetString("PageEditLessonPageChangeDefaultTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        public static string PageEditLessonRoom {
            get {
                return ResourceManager.GetString("PageEditLessonRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose subject.
        /// </summary>
        public static string PageEditLessonSubject {
            get {
                return ResourceManager.GetString("PageEditLessonSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose end time.
        /// </summary>
        public static string PageEditLessonTimeEnd {
            get {
                return ResourceManager.GetString("PageEditLessonTimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find time!.
        /// </summary>
        public static string PageEditLessonTimeNotFoundWarning {
            get {
                return ResourceManager.GetString("PageEditLessonTimeNotFoundWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose start time.
        /// </summary>
        public static string PageEditLessonTimeStart {
            get {
                return ResourceManager.GetString("PageEditLessonTimeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string PageEditSubjectCaption {
            get {
                return ResourceManager.GetString("PageEditSubjectCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string PageEditSubjectColor {
            get {
                return ResourceManager.GetString("PageEditSubjectColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to use custom color.
        /// </summary>
        public static string PageEditSubjectIsCustomColor {
            get {
                return ResourceManager.GetString("PageEditSubjectIsCustomColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PageEditSubjectName {
            get {
                return ResourceManager.GetString("PageEditSubjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A subject with this name already exists! Subject name will not be changed..
        /// </summary>
        public static string PageEditSubjectNameAlreadyUsedWarning {
            get {
                return ResourceManager.GetString("PageEditSubjectNameAlreadyUsedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is reserved! Subject name will not be changed..
        /// </summary>
        public static string PageEditSubjectNameNotAllowedWarning {
            get {
                return ResourceManager.GetString("PageEditSubjectNameNotAllowedWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The subject needs a valid name! Subject name will not be changed..
        /// </summary>
        public static string PageEditSubjectNeedsNameWarning {
            get {
                return ResourceManager.GetString("PageEditSubjectNeedsNameWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find subject!.
        /// </summary>
        public static string PageEditSubjectNotFound {
            get {
                return ResourceManager.GetString("PageEditSubjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teacher.
        /// </summary>
        public static string PageEditSubjectTeacher {
            get {
                return ResourceManager.GetString("PageEditSubjectTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to error.
        /// </summary>
        public static string PageErrorPageCaption {
            get {
                return ResourceManager.GetString("PageErrorPageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error data lost. An error report is no longer possible..
        /// </summary>
        public static string PageErrorPageDataLostWarning {
            get {
                return ResourceManager.GetString("PageErrorPageDataLostWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sorry! This error should not have happened..
        /// </summary>
        public static string PageErrorPageFirst {
            get {
                return ResourceManager.GetString("PageErrorPageFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not send..
        /// </summary>
        public static string PageErrorPageNo {
            get {
                return ResourceManager.GetString("PageErrorPageNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///I am using {0} version {1} and the error {2} occurred:
        ///{3}
        ///A short description from me:
        ///
        ///
        ///
        ///
        ///Additional information:
        ///{4}
        ///Navigation:
        ///{5}
        ///
        ///Kind Regards..
        /// </summary>
        public static string PageErrorPageReport {
            get {
                return ResourceManager.GetString("PageErrorPageReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable: Error report.
        /// </summary>
        public static string PageErrorPageReportSubject {
            get {
                return ResourceManager.GetString("PageErrorPageReportSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We would appreciate your error report to help us to resolve the issue in an upcoming patch..
        /// </summary>
        public static string PageErrorPageSecond {
            get {
                return ResourceManager.GetString("PageErrorPageSecond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private data like your timetable will not be included in the report. We might use your e-mail address to contact you for further questions concerning the error..
        /// </summary>
        public static string PageErrorPageThird {
            get {
                return ResourceManager.GetString("PageErrorPageThird", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes, send error report!.
        /// </summary>
        public static string PageErrorPageYes {
            get {
                return ResourceManager.GetString("PageErrorPageYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove {0} unused times?.
        /// </summary>
        public static string PageGeneralDataEditorCleanUpLessonTimesWarningPlural {
            get {
                return ResourceManager.GetString("PageGeneralDataEditorCleanUpLessonTimesWarningPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove one unused time?.
        /// </summary>
        public static string PageGeneralDataEditorCleanUpLessonTimesWarningSingular {
            get {
                return ResourceManager.GetString("PageGeneralDataEditorCleanUpLessonTimesWarningSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No times.
        ///Tap + to add times!.
        /// </summary>
        public static string PageGeneralDataEditorLessonTimeEmptyList {
            get {
                return ResourceManager.GetString("PageGeneralDataEditorLessonTimeEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to times.
        /// </summary>
        public static string PageGeneralDataEditorLessonTimes {
            get {
                return ResourceManager.GetString("PageGeneralDataEditorLessonTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lessons.
        ///Tap + to add lessons!.
        /// </summary>
        public static string PageGeneralDataEditorSubjectEmptyList {
            get {
                return ResourceManager.GetString("PageGeneralDataEditorSubjectEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subjects.
        /// </summary>
        public static string PageGeneralDataEditorSubjects {
            get {
                return ResourceManager.GetString("PageGeneralDataEditorSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string PageHomeworkOverviewAll {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by created date.
        /// </summary>
        public static string PageHomeworkOverviewByFromDate {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewByFromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by subject.
        /// </summary>
        public static string PageHomeworkOverviewBySubject {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewBySubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by due date.
        /// </summary>
        public static string PageHomeworkOverviewByToDate {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewByToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show homework by subject.
        /// </summary>
        public static string PageHomeworkOverviewFilter {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose subject.
        /// </summary>
        public static string PageHomeworkOverviewFilterFullMode {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewFilterFullMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subjects need to be created first before homework can be added..
        /// </summary>
        public static string PageHomeworkOverviewNoSubjectWarning {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewNoSubjectWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHOOSE ORDER.
        /// </summary>
        public static string PageHomeworkOverviewOrder {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove this task?.
        /// </summary>
        public static string PageHomeworkOverviewRemoveWarning {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewRemoveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subject.
        /// </summary>
        public static string PageHomeworkOverviewSubject {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No homework for this subject..
        /// </summary>
        public static string PageHomeworkOverviewSubjectEmptyList {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewSubjectEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to today.
        /// </summary>
        public static string PageHomeworkOverviewToday {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No homework today..
        /// </summary>
        public static string PageHomeworkOverviewTodayEmptyList {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewTodayEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tomorrow.
        /// </summary>
        public static string PageHomeworkOverviewTomorrow {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No homework until tomorrow.
        /// </summary>
        public static string PageHomeworkOverviewTomorrowEmptyList {
            get {
                return ResourceManager.GetString("PageHomeworkOverviewTomorrowEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string PageInfoPageCaption {
            get {
                return ResourceManager.GetString("PageInfoPageCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string PageInfoPageDesign {
            get {
                return ResourceManager.GetString("PageInfoPageDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey what are you doing down here. Get back to your school work :).
        /// </summary>
        public static string PageInfoPageEasterEgg {
            get {
                return ResourceManager.GetString("PageInfoPageEasterEgg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics.
        /// </summary>
        public static string PageInfoPageGraphics {
            get {
                return ResourceManager.GetString("PageInfoPageGraphics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We would love to hear your questions and suggestions for this app, but at this point we can only provide mail support in german and english. Continue writing a support mail?.
        /// </summary>
        public static string PageInfoPageLanguageWarning {
            get {
                return ResourceManager.GetString("PageInfoPageLanguageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support languages.
        /// </summary>
        public static string PageInfoPageLanguageWarningTitle {
            get {
                return ResourceManager.GetString("PageInfoPageLanguageWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello,
        ///I am using {0} version {1} and I have a question or an idea for future versions:
        ///
        ///
        ///
        ///
        ///
        ///Many thanks!
        ///Kind Regards..
        /// </summary>
        public static string PageInfoPageMailBody {
            get {
                return ResourceManager.GetString("PageInfoPageMailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: Questions and Ideas.
        /// </summary>
        public static string PageInfoPageMailSubject {
            get {
                return ResourceManager.GetString("PageInfoPageMailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programming.
        /// </summary>
        public static string PageInfoPageProgramming {
            get {
                return ResourceManager.GetString("PageInfoPageProgramming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string PageInfoPageRate {
            get {
                return ResourceManager.GetString("PageInfoPageRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to support mail.
        /// </summary>
        public static string PageInfoPageSupportMail {
            get {
                return ResourceManager.GetString("PageInfoPageSupportMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version {0}.
        /// </summary>
        public static string PageInfoPageVersion {
            get {
                return ResourceManager.GetString("PageInfoPageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to visit our website.
        /// </summary>
        public static string PageInfoPageWebsite {
            get {
                return ResourceManager.GetString("PageInfoPageWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        public static string PageLandscapeViewCaption {
            get {
                return ResourceManager.GetString("PageLandscapeViewCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free time.
        /// </summary>
        public static string PageLandscapeViewFreeTime {
            get {
                return ResourceManager.GetString("PageLandscapeViewFreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lessons..
        /// </summary>
        public static string PageLandscapeViewNoLesson {
            get {
                return ResourceManager.GetString("PageLandscapeViewNoLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}:{1:00}:{2:00} hours remaining..
        /// </summary>
        public static string PageLandscapeViewRemainingTimeFormat {
            get {
                return ResourceManager.GetString("PageLandscapeViewRemainingTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remaining time unknown..
        /// </summary>
        public static string PageLandscapeViewRemainingTimeUnknown {
            get {
                return ResourceManager.GetString("PageLandscapeViewRemainingTimeUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMETABLE - {0}. CALENDAR WEEK.
        /// </summary>
        public static string PageLandscapeWeekViewCaptionFormat {
            get {
                return ResourceManager.GetString("PageLandscapeWeekViewCaptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        public static string PageLandscapeWeekViewTimes {
            get {
                return ResourceManager.GetString("PageLandscapeWeekViewTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string PageMainPageAbout {
            get {
                return ResourceManager.GetString("PageMainPageAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No lessons.
        ///Tap + to add lessons!.
        /// </summary>
        public static string PageMainPageEmptyList {
            get {
                return ResourceManager.GetString("PageMainPageEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to even / odd - weeks.
        /// </summary>
        public static string PageMainPageEvenOddWeeks {
            get {
                return ResourceManager.GetString("PageMainPageEvenOddWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit times and subjects.
        /// </summary>
        public static string PageMainPageLessonTimeSubjects {
            get {
                return ResourceManager.GetString("PageMainPageLessonTimeSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress view.
        /// </summary>
        public static string PageMainPageProgressView {
            get {
                return ResourceManager.GetString("PageMainPageProgressView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string PageMainPageSettings {
            get {
                return ResourceManager.GetString("PageMainPageSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show even weeks.
        /// </summary>
        public static string PageMainPageShowEvenWeeks {
            get {
                return ResourceManager.GetString("PageMainPageShowEvenWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show odd weeks.
        /// </summary>
        public static string PageMainPageShowOddWeeks {
            get {
                return ResourceManager.GetString("PageMainPageShowOddWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change timetable.
        /// </summary>
        public static string PageMainPageSwitchTimetable {
            get {
                return ResourceManager.GetString("PageMainPageSwitchTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what is in the full version?.
        /// </summary>
        public static string PageMainPageTrialVersion {
            get {
                return ResourceManager.GetString("PageMainPageTrialVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week view.
        /// </summary>
        public static string PageMainPageWeekView {
            get {
                return ResourceManager.GetString("PageMainPageWeekView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is now the current timetable..
        /// </summary>
        public static string PageSelectTimetableActiveChangedFormat {
            get {
                return ResourceManager.GetString("PageSelectTimetableActiveChangedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to manage.
        /// </summary>
        public static string PageSelectTimetableCaption {
            get {
                return ResourceManager.GetString("PageSelectTimetableCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current timetable:.
        /// </summary>
        public static string PageSelectTimetableCurrent {
            get {
                return ResourceManager.GetString("PageSelectTimetableCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove timetable {0} from your SkyDrive?.
        /// </summary>
        public static string PageSelectTimetableDeleteSkyDriveWarning {
            get {
                return ResourceManager.GetString("PageSelectTimetableDeleteSkyDriveWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to remove timetable {0} with all its subjects, homework and dates?.
        /// </summary>
        public static string PageSelectTimetableDeleteWarning {
            get {
                return ResourceManager.GetString("PageSelectTimetableDeleteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No other timetables.
        ///Tap + to create new timetable..
        /// </summary>
        public static string PageSelectTimetableEmptyList {
            get {
                return ResourceManager.GetString("PageSelectTimetableEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable {0}.
        /// </summary>
        public static string PageSelectTimetableNamingFormat {
            get {
                return ResourceManager.GetString("PageSelectTimetableNamingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other timetables:.
        /// </summary>
        public static string PageSelectTimetableOther {
            get {
                return ResourceManager.GetString("PageSelectTimetableOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SkyDrive.
        /// </summary>
        public static string PageSelectTimetableSkyDriveCaption {
            get {
                return ResourceManager.GetString("PageSelectTimetableSkyDriveCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection..
        /// </summary>
        public static string PageSelectTimetableSkyDriveDisconnected {
            get {
                return ResourceManager.GetString("PageSelectTimetableSkyDriveDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading timetables....
        /// </summary>
        public static string PageSelectTimetableSkyDriveLoading {
            get {
                return ResourceManager.GetString("PageSelectTimetableSkyDriveLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No timetables available.
        ///Timetables are saved to the SkyDrive folder &apos;Timetables&apos;..
        /// </summary>
        public static string PageSelectTimetableSkyDriveReadyEmtpyString {
            get {
                return ResourceManager.GetString("PageSelectTimetableSkyDriveReadyEmtpyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetables located in your SkyDrive folder &apos;Timetables&apos;:.
        /// </summary>
        public static string PageSelectTimetableSkyDriveSubCaption {
            get {
                return ResourceManager.GetString("PageSelectTimetableSkyDriveSubCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        public static string PageSelectTimetableSkyDriveWait {
            get {
                return ResourceManager.GetString("PageSelectTimetableSkyDriveWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD.
        /// </summary>
        public static string PageSelectTimetableUpload {
            get {
                return ResourceManager.GetString("PageSelectTimetableUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differing times for some lessons.
        /// </summary>
        public static string PageTimetableSettingsCustomTimes {
            get {
                return ResourceManager.GetString("PageTimetableSettingsCustomTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The progress week view may not work correctly with this setting enabled..
        /// </summary>
        public static string PageTimetableSettingsCustomTimesInfo {
            get {
                return ResourceManager.GetString("PageTimetableSettingsCustomTimesInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string PageTimetableSettingsGeneral {
            get {
                return ResourceManager.GetString("PageTimetableSettingsGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Live Tile.
        /// </summary>
        public static string PageTimetableSettingsLiveTile {
            get {
                return ResourceManager.GetString("PageTimetableSettingsLiveTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Live tile updates..
        /// </summary>
        public static string PageTimetableSettingsLiveTileDescription {
            get {
                return ResourceManager.GetString("PageTimetableSettingsLiveTileDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background agents for ModernTimetable are disabled in the phone&apos;s settings..
        /// </summary>
        public static string PageTimetableSettingsLiveTileDisabledWarning {
            get {
                return ResourceManager.GetString("PageTimetableSettingsLiveTileDisabledWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch even and odd weeks.
        /// </summary>
        public static string PageTimetableSettingsSwitchEvenOddWeeks {
            get {
                return ResourceManager.GetString("PageTimetableSettingsSwitchEvenOddWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even and odd weeks switched successfully!.
        /// </summary>
        public static string PageTimetableSettingsSwitchEvenOddWeeksWarning {
            get {
                return ResourceManager.GetString("PageTimetableSettingsSwitchEvenOddWeeksWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        public static string PageTimetableSettingsTimes {
            get {
                return ResourceManager.GetString("PageTimetableSettingsTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable name.
        /// </summary>
        public static string PageTimetableSettingsTimetableName {
            get {
                return ResourceManager.GetString("PageTimetableSettingsTimetableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to full version.
        /// </summary>
        public static string PageTimetableSettingsTrial {
            get {
                return ResourceManager.GetString("PageTimetableSettingsTrial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase the ad-free full version for following features:
        ///- Week- and Progress view
        ///- Dates
        ///- Manage multiple timetables
        ///- SkyDrive.
        /// </summary>
        public static string PageTimetableSettingsTrialDescription {
            get {
                return ResourceManager.GetString("PageTimetableSettingsTrialDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show in Store.
        /// </summary>
        public static string PageTimetableSettingsTrialOpenStore {
            get {
                return ResourceManager.GetString("PageTimetableSettingsTrialOpenStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to weekdays.
        /// </summary>
        public static string PageTimetableSettingsWeekDays {
            get {
                return ResourceManager.GetString("PageTimetableSettingsWeekDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one weekday needs to be enabled. Weekday changes will not be saved..
        /// </summary>
        public static string PageTimetableSettingsWeekDaysWarning {
            get {
                return ResourceManager.GetString("PageTimetableSettingsWeekDaysWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMETABLE - DATES.
        /// </summary>
        public static string PageTitleDates {
            get {
                return ResourceManager.GetString("PageTitleDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMETABLE - HOMEWORK.
        /// </summary>
        public static string PageTitleHomework {
            get {
                return ResourceManager.GetString("PageTitleHomework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMETABLE - SETTINGS.
        /// </summary>
        public static string PageTitleSettings {
            get {
                return ResourceManager.GetString("PageTitleSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every month.
        /// </summary>
        public static string RepeatBehaviourMonthly {
            get {
                return ResourceManager.GetString("RepeatBehaviourMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One-time.
        /// </summary>
        public static string RepeatBehaviourNone {
            get {
                return ResourceManager.GetString("RepeatBehaviourNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every week.
        /// </summary>
        public static string RepeatBehaviourWeekly {
            get {
                return ResourceManager.GetString("RepeatBehaviourWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no connection to your SkyDrive. Maybe your is not connected to the internet. Try again later. Error: {0}.
        /// </summary>
        public static string SkyDriveHelperErrorWarning {
            get {
                return ResourceManager.GetString("SkyDriveHelperErrorWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection to your SkyDrive is currently not available..
        /// </summary>
        public static string SkyDriveHelperException {
            get {
                return ResourceManager.GetString("SkyDriveHelperException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free period.
        /// </summary>
        public static string SubjectFreeTime {
            get {
                return ResourceManager.GetString("SubjectFreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New subject {0}.
        /// </summary>
        public static string SubjectNewFormat {
            get {
                return ResourceManager.GetString("SubjectNewFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free time
        ///{0:ddd}.
        /// </summary>
        public static string TileMediumFreeTime {
            get {
                return ResourceManager.GetString("TileMediumFreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:t}
        ///{1}
        ///.
        /// </summary>
        public static string TileMediumLesson {
            get {
                return ResourceManager.GetString("TileMediumLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dates.
        /// </summary>
        public static string TileWideDatesPlural {
            get {
                return ResourceManager.GetString("TileWideDatesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} date.
        /// </summary>
        public static string TileWideDatesSingular {
            get {
                return ResourceManager.GetString("TileWideDatesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to free time
        ///{0:ddd} .
        /// </summary>
        public static string TileWideFreeTime {
            get {
                return ResourceManager.GetString("TileWideFreeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} homework.
        /// </summary>
        public static string TileWideHomeworkPlural {
            get {
                return ResourceManager.GetString("TileWideHomeworkPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} homework.
        /// </summary>
        public static string TileWideHomeworkSingular {
            get {
                return ResourceManager.GetString("TileWideHomeworkSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:t} - {1:t} {2} {3}
        ///.
        /// </summary>
        public static string TileWideLesson {
            get {
                return ResourceManager.GetString("TileWideLesson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect timetable.
        /// </summary>
        public static string TimetableDescriptionInvalidTimetable {
            get {
                return ResourceManager.GetString("TimetableDescriptionInvalidTimetable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable (No name).
        /// </summary>
        public static string TimetableDescriptionNoName {
            get {
                return ResourceManager.GetString("TimetableDescriptionNoName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time is supposed to move forwards, not backwards..
        /// </summary>
        public static string TimetableGetListedLessonsException {
            get {
                return ResourceManager.GetString("TimetableGetListedLessonsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not export Timetable..
        /// </summary>
        public static string TimetableIOExportError {
            get {
                return ResourceManager.GetString("TimetableIOExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not import the selected XML-File..
        /// </summary>
        public static string TimetableIOImportError {
            get {
                return ResourceManager.GetString("TimetableIOImportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read the Timetable-XML-File..
        /// </summary>
        public static string TimetableLoadParseException {
            get {
                return ResourceManager.GetString("TimetableLoadParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t read the Timetable-XML-File from the device..
        /// </summary>
        public static string TimetableLoadReadException {
            get {
                return ResourceManager.GetString("TimetableLoadReadException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable.
        /// </summary>
        public static string TimetableNewName {
            get {
                return ResourceManager.GetString("TimetableNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} lessons are assigned this subject(&quot;{0}&quot;). Really want to delete?.
        /// </summary>
        public static string TimetableRemoveSubjectWarningPluralFormat {
            get {
                return ResourceManager.GetString("TimetableRemoveSubjectWarningPluralFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One lesson is assigned this subject(&quot;{0}&quot;). Really want to delete?.
        /// </summary>
        public static string TimetableRemoveSubjectWarningSingularFormat {
            get {
                return ResourceManager.GetString("TimetableRemoveSubjectWarningSingularFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timetable name: {0}
        ///
        ///Homework: {1}
        ///
        ///Dates: {2}.
        /// </summary>
        public static string TimetableReportBody {
            get {
                return ResourceManager.GetString("TimetableReportBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0}: {1}.
        /// </summary>
        public static string TimetableReportDate {
            get {
                return ResourceManager.GetString("TimetableReportDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - {0}, to do until {1} (Created {2}): {3}.
        /// </summary>
        public static string TimetableReportHomework {
            get {
                return ResourceManager.GetString("TimetableReportHomework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None..
        /// </summary>
        public static string TimetableReportNone {
            get {
                return ResourceManager.GetString("TimetableReportNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMETABLE - REPORT, {0}.
        /// </summary>
        public static string TimetableReportSubject {
            get {
                return ResourceManager.GetString("TimetableReportSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not save the Timetable-XML-File on the device..
        /// </summary>
        public static string TimetableSaveFileInnerSaveException {
            get {
                return ResourceManager.GetString("TimetableSaveFileInnerSaveException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create the content for the Timetable-XML-File..
        /// </summary>
        public static string TimetableSaveFileInnerXmlException {
            get {
                return ResourceManager.GetString("TimetableSaveFileInnerXmlException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup failed. The current Timetable will be not saved to prevent further data loss..
        /// </summary>
        public static string TimetableSaveToFileBackupException {
            get {
                return ResourceManager.GetString("TimetableSaveToFileBackupException", resourceCulture);
            }
        }
    }
}
